name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 

    - name: Create C# project
      run: |
        dotnet new console -n GTweens
        cd GTweens

    - name: Copy repository contents to project
      run: |
        cp -r ../. .

    - name: Add NUnit
      run: dotnet add package NUnit

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-restore
